model:
  test_size: 0.2
  random_state: 42
  cv_folds: 5
  n_trials: 100

preprocessing:
  scaling_method: "standard"
  polynomial_degree: 2

optimization:
  direction: "maximize"
  n_trials: 100

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"